# Generated by Django 4.2.7 on 2024-03-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering_owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringcompany',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
