# Generated by Django 4.2.7 on 2024-03-10 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering_owners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cateringcompany',
            old_name='company_name',
            new_name='name',
        ),
    ]
