# Generated by Django 4.2.7 on 2024-03-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering_owners', '0002_alter_cateringcompany_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringcompany',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
