# Generated by Django 4.2.7 on 2024-03-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_english_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='english_level',
            field=models.CharField(choices=[('C2', 'C2'), ('C1', 'C1'), ('B2', 'B2'), ('B1', 'B1'), ('A2', 'A2'), ('A1', 'A1'), ('NONE', 'None')], default='NINGUNO', max_length=50),
        ),
    ]
