name: "Definici贸n de funcionalidad"
description: "Define una nueva caracter铆stica para este proyecto."
title: "[Feature]"
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        # ** Nueva funcionalidad**
  - type: textarea
    attributes:
      label: "Descripci贸n de la funcionalidad. (Misma descripci贸n que en el product backlog)"
      description: "Proporciona una descripci贸n clara y concisa de lo que implica la funcionalidad."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Contexto adicional"
      description: "A帽ade cualquier otro contexto o informaci贸n adicional sobre el problema aqu铆."
    validations:
      required: false
